export const SET_MOVIE_LIST = "SET_MOVIE_LIST";
export const CHOOSE_MOVIE = "CHOOSE_MOVIE";
export const SET_SEARCH_INFO = "SET_SEARCH_INFO";
export const SET_CREDENTIAL = "SET_CREDENTIAL";
export const SET_IS_LOGGING_IN = "SET_IS_LOGGING_IN";
export const SET_SHOWTIME = "SET_SHOWTIME";
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_SEARCHED_ACCOUNT = "SET_SEARCHED_ACCOUNT";
export const SET_THEATER_SYSTEM_LIST = "SET_THEATER_SYSTEM_LIST";
export const CHOOSE_THEATER_SYSTEM = "CHOOSE_THEATER_SYSTEM";
export const SET_THEATER_LIST = "SET_THEATER_LIST";
export const CHOOSE_THEATER = "CHOOSE_THEATER";
export const SET_SHOWING = "SET_SHOWING";
export const SET_SHOWTIME_BY_MAPHIM = "SET_SHOWTIME_BY_MAPHIM";
export const SET_IS_FINISHED_LOADING_SHOWTIME =
  "SET_IS_FINISHED_LOADING_SHOWTIME";
export const SET_MESSAGE_BOX = "SET_MESSAGE_BOX";
